### PR TITLE
Accessibility checks and changes

### PR DESCRIPTION
**Pull request by acolombo1**
ACCESSIBILITY REPORT

Page titles: The page title was already implemented. No issues found.

Image text alternatives: Issues found: Alts were already in the document, but we updated a couple of alt texts (remove "icon" word).

Text headings: Hierarchy was already in place, no need to refactor headings. No issues found.

Color contrast: Issue found: Updated card titles to increase contrast and thus readability, with a black background.

Resize: Issues found: The text didn’t get larger when you change the setting in Chrome, so we changed all font sizes from px to em. Font changes to large and small don’t crop texts (no issues found here).

Interaction: Web page interaction with the keyboard was already in place for the current document. No issues found.

Moving content: The page has no moving elements but the title logo, but it does not blink or flash. No issues found.

Multimedia: No video or audio in portfolio (yet..). No issues found.

The basic structure of the page: The webpage was tested without CSS (deleted using devtools), the structure seems logical and there's no need for extra refactoring. No issues found.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
> no need to refactor headings.
> 
> Color contrast: Updated card titles to increase contrast and thus readability, with a black background.
> 
> Text readability: Text as an image is not present. The text do




 Your report should also include:
- [Resize](https://www.w3.org/WAI/test-evaluate/preliminary/#resize)

#### Each point on  your list needs to include the result of your evaluation:
If everything was ok about a point, make a statement about that (e.g. "Page titles - no issues found").

- [x] Kindly add your report  to the description of your pull request

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ GitHub flow was correctly used



## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — APPROVED** [review]
Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by acolombo1** [comment]
Hi @bimbolabuari, I received the email from your review, but I still see the "Review Pending" status (even after refreshing several times) in my Dashboard Progress. Should I contact student success or something? Thank you.

**Pull request merged**
